### ISSUE TITLE
Can't go to jump key mode on timeout

### ISSUE THREAD

**Issue by taromero** [t9md/vim-smalls#6]
I type `s`, type a few characters and wait for the timeout but nothing happens. I would expect that after 0.5s the letters would display on top of the options for me to select but this doesn't happen. I have to press Tab+Enter for this to happen.

**Comment by t9md** [comment]
Paste your smalls config.

**Comment by taromero** [comment]
Here it is:
```
Plugin 't9md/vim-smalls'
nmap s <Plug>(smalls)
omap s <Plug>(smalls)
xmap s <Plug>(smalls)
```

**Comment by t9md** [comment]
You need add some configuration at first to work 0.5s timeout auto jump feature.
See `:help smalls`, especially for variable `*g:smalls_auto_jump_timeout` and `g:smalls_auto_jump_min_input_length`.
I don't want to repeat things written in help file.

**Comment by taromero** [comment]
Thanks, that did it. For reference here are the lines I've added:
```
let g:smalls_auto_jump = 1 
let g:smalls_auto_jump_min_input_length = 2 
let g:smalls_auto_jump_timeout = 0.3
```

It might be a good idea to provide those on the sample config at the README file, is this behavior is shown on the sample gif (so I expected it to be the default).

**Comment by t9md** [comment]
Thanks for feedback.
I don't want auto_jump to default.
I want explicitly instruct to show jump label.
My preference(my configuration) is here. I like auto_set feature, which enable you to automatically move cursor to target position if there is one candidate left.

```Vim
nmap s <Plug>(smalls)
xmap s <Plug>(smalls)
omap s <Plug>(smalls)
let g:smalls_auto_set = 1
let g:smalls_auto_set_min_input_length = 1
```
