### ISSUE TITLE
Some modifications I would like to make

### ISSUE THREAD

**Issue by colwem** [t9md/vim-smalls#8]
I created a description of a tool I would like here https://github.com/colwem/vim-tunnel-vision

Your plugin is getting pretty close to what I want so I thought I would fork it and see if I can make the changes I need.  I've never done anything with vimscript though and thought I'd ask if you're interested in helping me with these additional features.

**Comment by t9md** [comment]
Lets create your own plugin. If you want to fork my vin-smalls and release it, Im OK as long as you credit me for that.
For helping you, I have no time to help someone else, and don't want to use my time for explaining how my code is working.
I'm no longer using vim-smalls anymore.
